### PR TITLE
Add usage of type field

### PR DESCRIPTION
**Pull request by coders-kitchen**
This changes will add the usage of the type field with dedicated URIs per status code.

it allows additionally the client to specify a dedicated URI for the type information for it's own usage so that he is able to direct the consumer to the specific information.

As the target https://httpstatuses.com/{STATUS_CODE} is used.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Specifying a custom type URI when translating from an exception to a problem could potentially be useful. Although in most cases the exception is probably already a custom implementation and the easier way would be to just let it implement the `Problem` interface.

Defaulting to <http://httpstatuses.com> as a problem type in my opinion violates the RFC:

> When an HTTP API needs to define a response that indicates an error
   condition, it might be appropriate to do so by defining a new problem
   type.
>
> Before doing so, it's important to understand what they are good for,
   and what's better left to other mechanisms.
>
> Problem details are not a debugging tool for the underlying
   implementation; rather, they are a way to expose greater detail about
   the HTTP interface itself.  Designers of new problem types need to
   carefully consider the Security Considerations (Section 5), in
   particular, the risk of exposing attack vectors by exposing
   implementation internals through error messages.
>
> Likewise, truly generic problems -- i.e., conditions that could
   potentially apply to any resource on the Web -- are usually better
   expressed as plain status codes.  For example, a "write access
   disallowed" problem is probably unnecessary, since a 403 Forbidden
   status code in response to a PUT request is self-explanatory.


[RFC 7807: Section 4 Defining New Problem Types](https://tools.ietf.org/html/rfc7807#section-4)

> The "about:blank" URI [RFC6694], when used as a problem type,
   indicates that the problem has no additional semantics beyond that of
   the HTTP status code.

[RFC 7807: Section 4.2 Predefined Problem Types](https://tools.ietf.org/html/rfc7807#section-4.2)

**Comment by coders-kitchen** [comment]
Thanks for the hint to the RFC. I got the point.

I would propose to 

- remove the defaulting to "https://httpstatuses.com/<>"
- leave the option of specifying an additional type URI as it is now

This would allow the clients to stick to the existing problem object, when an own one is not necessary. But allow them to specify the type if needed.

What do you think?

**Comment by whiskeysierra** [comment]
> What do you think?

:+1:

**Comment by coders-kitchen** [comment]
👍  I'll change it and update the pull request

**Comment by coders-kitchen** [comment]
Changes are made :)

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
