### PR TITLE
Added support for @ResponseStatus

### LINKED ISSUE #107: Support ResponseStatus annotation
I currently use
```java
    @Override
    public ResponseEntity<Problem> handleThrowable(
        final Throwable throwable,
        final NativeWebRequest request) {
        ResponseStatus responseStatus = AnnotationUtils.findAnnotation(throwable.getClass(), ResponseStatus.class);
        if (responseStatus != null) {
            Problem problem = Problem.builder()
                .withStatus(new HttpStatusAdapter(responseStatus.value()))
                .withTitle(responseStatus.value().getReasonPhrase())
                .withDetail(responseStatus.reason())
                .build();
            return create(throwable, problem, request);
        } else {
            return create(Response.Status.INTERNAL_SERVER_ERROR, throwable, request);
        }
    }
```
to handle exceptions annotated with ResponseStatus but I think it would be nicer to have it handled directly in the lib.

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #107

@cbornet Feel free to take a look

### CODE REVIEW

**Comment by cbornet** [comment]
👍

**Comment by cbornet** [comment]
@whiskeysierra Do you think it would be possible to use the `reason` field of `ResponseStatus` to fill `detail` when `throwable.getMessage()` is null ?

**Comment by whiskeysierra** [comment]
Sure. Can you open another issue for this?

**Comment by cbornet** [comment]
Actually, for consistency it should probably be the `title` that should be filled with `reason`.
Yes I can open an issue and probably even a PR.

**Comment by whiskeysierra** [comment]
Yes title, correct.

**Comment by cbornet** [comment]
I did this in my code
```java
    @Override
    public ThrowableProblem toProblem(final Throwable throwable) {
        final StatusType status = Optional.of(resolveResponseStatus(throwable))
            .<StatusType>map(ResponseStatusAdapter::new)
            .orElse(Status.INTERNAL_SERVER_ERROR);


        return toProblem(throwable, status);
    }

    public static class ResponseStatusAdapter implements StatusType {

        private int code;
        private String reason;

        public ResponseStatusAdapter(ResponseStatus responseStatus) {
            this.code = responseStatus.code().value();
            this.reason = responseStatus.reason().isEmpty() ? responseStatus.value().getReasonPhrase() : responseStatus.reason();
        }

        @Override
        public int getStatusCode() {
            return code;
        }

        @Override
        public String getReasonPhrase() {
            return reason;
        }
    }

    public ResponseStatus resolveResponseStatus(final Throwable type) {
        @Nullable final ResponseStatus candidate = findMergedAnnotation(type.getClass(), ResponseStatus.class);
        return candidate == null && type.getCause() != null ? resolveResponseStatus(type.getCause()) : candidate;
    }
```
does it seem OK for you ?

**Comment by whiskeysierra** [comment]
Can we make that adapter package private? I'm also not sure whether the decision `responseStatus.reason().isEmpty() ? responseStatus.value().getReasonPhrase() : responseStatus.reason()` should be in there or somewhere else.

**Comment by cbornet** [comment]
@whiskeysierra I can store the ResponseStatus and extract the code and reason in the getters like is done in HttpStatusAdapter if you want.

**Pull request merged**
