### PR TITLE
Add support for Spring BindException

### LINKED ISSUE #85: BindException validation built-in support
I would discuss with you if `org.springframework.validation.BindException` could be a great candidate to be a built-in managed exception.

Indeed when you're validating query params rather than post body like following

```java
@RequestMapping(path = "/handler-invalid-query-strings", method = GET)
public ResponseEntity<String> validRequestQueryStrings(@Valid final PageRequest pageRequest) {
    return ResponseEntity.ok("done");
}
```

With `PageRequest` looks like

```java
@Data
public final class PageRequest {

    @Min(value = 0)
    private int page = 0;

    @Min(value = 1)
    private int size = 50;
}
```

If you try

```java
@Test
public void invalidRequestQueryParams() throws Exception {
    mvc().perform(request(GET, "http://localhost/api/handler-invalid-query-strings?page=-1"))
         .andExpect(status().isBadRequest());
}
```

I will fail because `500` status code will be returned after Spring will throw `org.springframework.validation.BindException`

---

A bit off-topic, but can explain why:

 Spring `MethodValidationPostProcessor` works great with `zalando:problem-spring-web`, indeed if you replace previous `GetMapping` with following:

```java
@RequestMapping(path = "/handler-invalid-query-strings", method = GET)
public ResponseEntity<String> validRequestQueryStrings(@Min(value = 0) @RequestParam(value = "page", defaultValue = "0") int page,
        @Min(value = 1) @RequestParam(value="limit", defaultValue = "50") int limit) {
    return ResponseEntity.ok("done");
}
```

I will work but since method parameter **name is removed after compilation** the result looks like:

```json
{  
   "violations":[  
      {  
         "field":"getUsers.arg0",
         "message":"must be greater than or equal to 0"
      }
   ],
   "status":400,
   "type":"https://zalando.github.io/problem/constraint-violation",
   "title":"Constraint Violation"
}
```

As you can see `field` is equals to `getUsers.arg0` which is no really user-friendly.
That why I used to create a intermediate object (`DTO`?) for validation even for `GET` parameters.

### PR DESCRIPTION
**Pull request by kakawait**
fixes #85

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@kakawait Are you planning more changes here? e.g. dropping the object name prefix?

**Comment by kakawait** [comment]
@whiskeysierra No I'm not. I use to create a PR per subject

**Comment by kakawait** [comment]
@whiskeysierra you prefer that I add everything on that PR?

**Comment by whiskeysierra** [comment]
No strong preference. I just didn't want to merge this one if you're still working on it. I'll merge it now.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by kakawait** [comment]
@whiskeysierra no prob, usually I add `[WIP]` on merge title (strong usage on *GitLab* I used to do that)

**Pull request merged**
