### PR TITLE
Bump multiple dependencies

### PR DESCRIPTION
**Pull request by MALPI**
Bump version of

- Spring
- Spring Boot
- Spring-Security
- Jackson-Databind

Upgrade the dependency check plugin in order to make it work again.

As Spring and transitive dependencies like snakeyaml and others come with CVE's that are considered false positives I deactivated for now the failing build on cve.

Moreover I filed #832 in order to remove the plugin.

### CODE REVIEW

**Comment by MALPI** [comment]
👍

**Comment by MALPI** [comment]
@danielrohe please take a look

**Comment by danielrohe** [comment]
Does it make sense to adjust specific versions. This library will only run as part of another application where developers will manage versions using either spring boot, do it manually or use any other kind of dependency management tool. With this they will override the versions which are set in this pom.xml. So do we need to do the effort in bumping versions in a library?

**Comment by whiskeysierra** [comment]
You need to find a way to test this library against newer versions of its dependencies.
Bumping the versions in this project is one way to do it.

**Comment by danielrohe** [comment]
:+1:

**Pull request merged**
