### PR TITLE
Update project to Spring 6 and Spring Boot 3

### LINKED ISSUE #768: Spring Boot 3 support
Hi everything is working as expected, except these 3 imports: SB3 has migrated to jakarta namespace.

https://github.com/zalando/problem-spring-web/blob/0f62aa09f64a9cf69e46171542808e3d4c2a7a09/problem-spring-web/src/main/java/org/zalando/problem/spring/web/advice/security/SecurityProblemSupport.java#L15-L17

### PR DESCRIPTION
**Pull request by cemo**
## Description
Upgraded dependencies such as spring boot 3, spring 6 etc... Polished pom files.

- All tests are passing. 
- Coverage slightly has increased.
- All major dependencies are upgraded.
- All pom files are polished.

Note that Spring Framework 6 requires java 17 as a baseline. I updated minimum required version as java 17. 

Fixes #768 

## Motivation and Context
In order to use  problem library with Spring Boot 3, we need a compatible version.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by deicon** [comment]
Any Timeline for this to be merged ?

**Comment by MALPI** [comment]
Hey there,

Thanks for you contribution!

We will take care of it the next days!

**Comment by IsaSalemHame** [comment]
Any update?

**Comment by deicon** [comment]
We managed to replace it with the default spring implementation.

**Comment by cemo** [comment]
@deicon Honestly we did same :) Will you bring something new?

**Comment by radzikp** [comment]
Hi guys, any ETA for this change? Thanks!

**Comment by MALPI** [comment]
Hey @radzikp,

actually @danielrohe and myself were discussing how to proceed with the library in general in the light of the Problem support within Spring itself but didn't come to a conclusion yet.

See https://github.com/zalando/problem-spring-web/issues/817 & https://github.com/zalando/problem/issues/437

In any case this discussion takes longer than expected, so I will pickup work on this again.

**Comment by MALPI** [comment]
👍

**Pull request merged**
