### PR TITLE
Release 0.24.0

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by DanielFran** [comment]
@whiskeysierra Did you forget to update problem version to latest version?
It still target v. 0.22.0:
<problem.version>0.22.0</problem.version>

**Comment by whiskeysierra** [comment]
It wasn't available in central then. I'll wait for dependabot to update it.

**Comment by DanielFran** [comment]
Will you create another version then? I see that the version is already available...

**Comment by whiskeysierra** [comment]
Sure

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Pull request merged**
