### PR TITLE
Upgrade to problem 0.20.0

### PR DESCRIPTION
**Pull request by cbornet**
Due to breaking change https://github.com/zalando/problem/issues/51

### CODE REVIEW

**Comment by cbornet** [comment]
I'm happy we did the class replication since migrating is only changing some imports :smile:

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
@cbornet I released this as 0.20.0 to central. Thanks for the contribution! :tada:

**Comment by cbornet** [comment]
Great ! I can proceed with my JHipster PR, thanks !

**Pull request merged**
