### PR TITLE
Fix spring-security configuration for webmvc

### LINKED ISSUE #501: Unusual Behavior when Integrating with Spring Boot v2.3.3.RELEASE
When I set up a new Spring Boot web project using the latest version with this library (v0.25.2), all routes are unsecure by default.

## Description

Initially, I had a project which overrode the default `WebSecurityConfigurerAdapter` provided by Spring. In this project, I had added this library, and had injected `SecurityProblemSupport` into my own adapter (initial thought was I had to inject it; upon seeing that `SecurityConfiguration` was already supplied, I then made attempts without injecting it). This cause **very** unusual problems, the biggest being intermittent freezing during start up. To separate concerns, I created a simple project, and notice even more unusual patterns happening, such as the routes being unsecure by default. In the simple project, both `SecurityConfiguration` and `DefaultConfigurerAdapter` (Spring default) are initialized. If I override it and flip the order, I get the authentication errors, but no problem responses.

## Expected Behavior

1. `exceptionHandling` should apply to all security configurations.
2. Default configuration (i.e. user does not provide their own `WebSecurityConfigurerAdapter`) should be secure, and should return problem responses.

## Actual Behavior

1. `exceptionHandling` does not apply to all security configurations.
2. Default configuration is unsecure; and when swapping the order does not return problem responses.

## Possible Fix

Not sure. When testing with multiple `WebSecurityConfigurerAdapter`'s, the `HttpSecurity` instances don't follow a pattern of inheritance, which I thought this library was going for (i.e. `org.zalando.problem.spring.web.autoconfigure.security.SecurityConfiguration` as lowest order, which all other instances of `WebSecurityConfigurerAdapter` would inherit the exception handling).

## Steps to Reproduce

1. Set up new project using [Spring Initializr](https://start.spring.io/) (add Spring Web as dependency)
2. Add this library as a dependency
3. Set up a basic controller route
4. Calling the controller route should go through the security layer

## Context

Trying to use this library (the Spring Boot starter) with the default auto-configuration.

## Your Environment

* Version used: 0.25.2
* Java Version:
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+16-SA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+16-SA (build 11.0.7+10-LTS, mixed mode)
```

### LINKED ISSUE #582: InsufficientAuthenticationException being handled as HTTP 500 instead of 401
I'm using Springboot 2..3.4.RELEASE and problem-spring-web 0.25.0.

When trying to make a request to the API with no token a InsufficientAuthenticationException is thrown, in this case the HTTP status code should be 401, but problem library is handling it as status code 500.
```json
{
  "title": "Internal Server Error",
  "status": 500,
  "detail": "Full authentication is required to access this resource"
}
```
```terminal
2021-01-08 12:11:32.898 ERROR 24769 --- [nio-8080-exec-1] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource
...
```
### Spring security
```java
@KeycloakConfiguration
@Import(SecurityProblemSupport.class)
public class KeycloakSecurityConfig extends KeycloakWebSecurityConfigurerAdapter {

    @Autowired
    private SecurityProblemSupport problemSupport;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http
            .exceptionHandling()
            .authenticationEntryPoint(problemSupport)
            .accessDeniedHandler(problemSupport)
        .and()
            .cors().and().csrf().disable()
            .authorizeRequests()
            .antMatchers(HttpMethod.OPTIONS,"/swagger-ui.html#/**").permitAll()
            .anyRequest()
            .authenticated();
    }
...
```
### Controller Advice
```java
@ControllerAdvice
public class SecurityExceptionHandler implements SecurityAdviceTrait {

}
```
In version 0.23.0 works as expected.
```json
{
  "title": "Unauthorized",
  "status": 401,
  "detail": "Full authentication is required to access this resource"
}
```
```terminal
2021-01-08 12:21:41.871  WARN 26529 --- [nio-8080-exec-1] o.z.p.spring.web.advice.AdviceTrait      : Unauthorized: Full authentication is required to access this resource
```

### PR DESCRIPTION
**Pull request by aafwu00**
## Description
When spring security configuration with `WebSecurityConfigurerAdapter`, then throw IllegalStateException with message(`Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one`)
`WebSecurityConfigurerAdapter` loaded  `spring.factories` file when default security configuration. Add `ProblemHttpConfigur`, Using this meachnism is solved that problem.
But, If not using `WebSecurityConfigurerAdapter`, `spring.factories` is not working. so added `ProblemSecurityBeanPostProcessor` will be configure exception handling

## Motivation and Context
This fixes #501, #573 and also resolves #582

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by aafwu00** [comment]
@whiskeysierra  Thank you for your feedback. I fixed test coverage.

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@aafwu00 Can you gpg-sign your commits?
See https://docs.github.com/articles/about-gpg/

**Comment by aafwu00** [comment]
@whiskeysierra OK, I'll make another PR.

**Pull request closed without merging**
