### PR TITLE
Use @Configuration(proxyBeanMethods=false) to avoid unnecessary gener…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…ation of cglib proxies.Cglib proxy creation can be an expensive operation.

Similar to spring-projects/spring-boot#9068

I think this is a breaking change if somebody calls methods on the configuration classes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Can you sign your commits?

**Comment by PascalSchumacher** [comment]
> Can you sign your commits?

I updated the commit to add `Signed-off-by` (not sure if that was what you requested?).

**Comment by whiskeysierra** [comment]
No, it's this one: https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by PascalSchumacher** [comment]
To much for work for one trival change. Sorry.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Fair enough. I disabled the check for now.

**Pull request merged**
